### ISSUE TITLE
[W ..\aten\src\ATen\native\Copy.cpp:162] Warning: Casting complex values to real discards the imaginary part (function operator ())

### ISSUE THREAD

**Issue by s0966066980** [jdg900/UID-FDK#1]
Does this affect the result?

**Comment by jdg900** [comment]
In our experiment, it didn't affect the result.

Thank you!

**Comment by s0966066980** [comment]
Thanks for your reply
but , DIV2K_N need to add noise by itself?

**Comment by jdg900** [comment]
Thank you for your interest!

As you can see dataloader.py, when we load the dataset, the noise is added to DIV2K_N according to noise level.

I hope that it will be helpful for your question.

Thank you!
